services:
  fastsurfer:
    image: deepmi/fastsurfer:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../data:/data
      - ./output:/output
      - ./fs_license:/fs_license
    command: [
      "--fs_license", "/fs_license/license.txt", # provide your own license
      "--t1", "/data/sub-01_ses-01_sample-brain_res-494um_space-FSInput_XPCT.nii.gz",
      "--sid", "sub-01",
      "--sd", "/output",
      "--parallel",
      "--3T"
    ]
    user: "1000:1000" # edit with your own
    restart: "no"
